version: '3'

services:

    app:
        build: ./app
        ports:
            - "80:80"
        depends_on:
            - "db"
        restart: always
    db: 
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: harunamywife
        volumes:
            - ./sqls:/docker-entrypoint-initdb.d/:ro
        restart: always

    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - "db"
        restart: always
